image: node:10.21.0
cache:
   key: ${CI_COMMIT_REF_SLUG}
   paths:
      - .yarn
before_script:
   - cd dnapp
   - yarn install
   - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
stages:
   - deploy
expo-deployements:
   stage: deploy
   only:
      - master
   script:
      - USER=$EXPO_USERNAME PASS=$EXPO_PASSWORD CHANNEL=default npm run deploy
      - npm run build-android
expo-development:
   stage: deploy
   except:
      - master
   script:
      - USER=$EXPO_USERNAME PASS=$EXPO_PASSWORD CHANNEL=dev npm run deploy
